"""added constant_values in campagain

Revision ID: 16e53094325a
Revises: c04d0b6069e0
Create Date: 2026-01-26 19:37:07.988485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16e53094325a'
down_revision: Union[str, Sequence[str], None] = 'c04d0b6069e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('constants_values', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('newsletter_template_versions', sa.Column('constants', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.drop_column('newsletter_template_versions', 'variables')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newsletter_template_versions', sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False))
    op.drop_column('newsletter_template_versions', 'constants')
    op.drop_column('campaigns', 'constants_values')
    # ### end Alembic commands ###
