"""newsletter templates v3

Revision ID: 4380e658f93c
Revises: 12ed19dc76f2
Create Date: 2026-01-25 01:02:02.791932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4380e658f93c'
down_revision: Union[str, Sequence[str], None] = '12ed19dc76f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletter_template_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['newsletter_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletter_template_assets_company_id'), 'newsletter_template_assets', ['company_id'], unique=False)
    op.create_index(op.f('ix_newsletter_template_assets_template_id'), 'newsletter_template_assets', ['template_id'], unique=False)
    op.drop_index(op.f('ix_template_assets_company_id'), table_name='template_assets')
    op.drop_index(op.f('ix_template_assets_template_id'), table_name='template_assets')
    op.drop_table('template_assets')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_assets',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('template_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('file_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('template_assets_company_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['newsletter_templates.id'], name=op.f('template_assets_template_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('template_assets_pkey'))
    )
    op.create_index(op.f('ix_template_assets_template_id'), 'template_assets', ['template_id'], unique=False)
    op.create_index(op.f('ix_template_assets_company_id'), 'template_assets', ['company_id'], unique=False)
    op.drop_index(op.f('ix_newsletter_template_assets_template_id'), table_name='newsletter_template_assets')
    op.drop_index(op.f('ix_newsletter_template_assets_company_id'), table_name='newsletter_template_assets')
    op.drop_table('newsletter_template_assets')
    # ### end Alembic commands ###
