"""

Revision ID: c04d0b6069e0
Revises: bc35b8df7197
Create Date: 2026-01-26 19:12:05.980261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c04d0b6069e0'
down_revision: Union[str, Sequence[str], None] = 'bc35b8df7197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newsletter_templates', sa.Column('constants', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.drop_column('newsletter_templates', 'variables')
    op.create_index(op.f('ix_subscribers_subscriber_email'), 'subscribers', ['subscriber_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscribers_subscriber_email'), table_name='subscribers')
    op.add_column('newsletter_templates', sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False))
    op.drop_column('newsletter_templates', 'constants')
    # ### end Alembic commands ###
