"""Migration of username on subscribers

Revision ID: d493eb9aaf6e
Revises: 3_fix_campaign_send_logs_columns
Create Date: 2026-01-26 18:59:49.433424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd493eb9aaf6e'
down_revision: Union[str, Sequence[str], None] = '3_fix_campaign_send_logs_columns'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_campaign_send_logs_campaign_id'), 'campaign_send_logs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_send_logs_status'), 'campaign_send_logs', ['status'], unique=False)
    op.create_index(op.f('ix_campaign_send_logs_subscriber_email'), 'campaign_send_logs', ['subscriber_email'], unique=False)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.drop_constraint(op.f('campaigns_template_id_fkey'), 'campaigns', type_='foreignkey')
    op.create_foreign_key(None, 'campaigns', 'newsletter_templates', ['template_id'], ['id'], ondelete='SET NULL')
    op.add_column('subscribers', sa.Column('username', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscribers', 'username')
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.create_foreign_key(op.f('campaigns_template_id_fkey'), 'campaigns', 'newsletter_templates', ['template_id'], ['id'])
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_campaign_send_logs_subscriber_email'), table_name='campaign_send_logs')
    op.drop_index(op.f('ix_campaign_send_logs_status'), table_name='campaign_send_logs')
    op.drop_index(op.f('ix_campaign_send_logs_campaign_id'), table_name='campaign_send_logs')
    # ### end Alembic commands ###
